version: "3"

services:
  database:
    container_name: iam_db
    image: mariadb
    environment:
      MARIADB_DATABASE: "iam"
      MARIADB_ROOT_PASSWORD: "Qwer1234!"
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    networks:
      - network

  application:
    container_name: iam_web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://iam_db:3306/iam
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Qwer1234!"
      KEYCLOAK_URI: http://keycloak:8180/auth
      REALM: SpringBootKeycloakApp
    depends_on:
      - database
      - keycloak
    networks:
      - network

  postgres:
    image: postgres
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - network

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    ports:
      - "8180:8180"
    command:
      - "-Djboss.socket.binding.port-offset=100"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.realmName=myrealm"
      - "-Dkeycloak.migration.file=/tmp/keycloak.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"

    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_IMPORT: /tmp/keycloak.json
    volumes:
      - ./keycloak.json:/tmp/keycloak.json
    depends_on:
      - postgres
    networks:
      - network

networks:
  network:
    driver: bridge